#define BLACK  CRGB::Black
#define GREEN  CRGB::Green
#define RED    CRGB::Red
#define BLUE   CRGB::Blue
#define BROWN  0x893000
#define YELLOW  CRGB::Yellow
#define LIGHTGREEN 0x80ff80

const CRGB FRAME1[NUM_LEDS] PROGMEM = {
  BLACK, BLACK, BLACK, GREEN, RED, BLACK, BLACK, BLACK, 
	BLACK, BLACK, GREEN, RED, GREEN, GREEN, BLACK, BLACK, 
	BLACK, BLACK, GREEN, GREEN, GREEN, RED, BLACK, BLACK, 
	BLACK, RED, GREEN, RED, GREEN, GREEN, GREEN, BLACK, 
	GREEN, GREEN, GREEN, GREEN, GREEN, RED, GREEN, GREEN, 
	GREEN, RED, GREEN, RED, GREEN, GREEN, GREEN, GREEN, 
	BLACK, BLACK, BLACK, BROWN, BROWN, BLACK, BLACK, BLACK, 
	BLACK, BLACK, BLACK, BROWN, BROWN, BLACK, BLACK, BLACK
};

const CRGB FRAME2[NUM_LEDS] PROGMEM = {
  BLACK, BLACK, BLACK, BLUE, GREEN, BLACK, BLACK, BLACK, 
	BLACK, BLACK, BLUE, GREEN, GREEN, GREEN, BLACK, BLACK, 
	BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, 
	BLACK, GREEN, BLUE, GREEN, BLUE, GREEN, GREEN, BLACK, 
	GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLUE, GREEN, 
	GREEN, GREEN, BLUE, GREEN, BLUE, GREEN, GREEN, GREEN, 
	BLACK, BLACK, BLACK, BROWN, BROWN, BLACK, BLACK, BLACK, 
	BLACK, BLACK, BLACK, BROWN, BROWN, BLACK, BLACK, BLACK
};

const CRGB FRAME3[NUM_LEDS] PROGMEM = {
  BLACK, BLACK, BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, 
	BLACK, BLACK, GREEN, GREEN, YELLOW, GREEN, BLACK, BLACK, 
	BLACK, BLACK, YELLOW, GREEN, GREEN, GREEN, BLACK, BLACK, 
	BLACK, GREEN, GREEN, YELLOW, GREEN, YELLOW, GREEN, BLACK, 
	GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, YELLOW, 
	GREEN, YELLOW, GREEN, YELLOW, GREEN, YELLOW, GREEN, GREEN, 
	BLACK, BLACK, BLACK, BROWN, BROWN, BLACK, BLACK, BLACK, 
	BLACK, BLACK, BLACK, BROWN, BROWN, BLACK, BLACK, BLACK
};

const CRGB* const FRAMES[] PROGMEM = {FRAME1, FRAME2, FRAME3};
#define FRAMES_NUM 3