#define BLACK  CRGB::Black
#define GREEN  CRGB::Green
#define RED    CRGB::Red
#define BLUE   CRGB::Blue
#define BROWN  0x893000
#define YELLOW CRGB::Yellow
#define WHITE  CRGB::White
#define GRAY	 0xc0c0c0
#define LIGHTGREEN 0x80ff80

const CRGB FRAME1[NUM_LEDS] PROGMEM = {
  BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, 
	BLACK, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, 
	GRAY, BLACK, BLACK, WHITE, BLACK, BLACK, WHITE, GRAY, 
	GRAY, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, GRAY, 
	GRAY, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, GRAY, 
	GRAY, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, GRAY, 
	BLACK, GRAY, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, GRAY, BLACK, 
	BLACK, BLACK, GRAY, GRAY, GRAY, GRAY, BLACK, BLACK
};

const CRGB FRAME2[NUM_LEDS] PROGMEM = {
  BLACK, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, BLACK, 
	BLACK, BLACK, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, 
	GRAY, BLACK, WHITE, BLACK, BLACK, WHITE, BLACK, GRAY, 
	GRAY, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, GRAY, 
	GRAY, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, GRAY, 
	GRAY, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, GRAY, 
	BLACK, GRAY, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, LIGHTGREEN, GRAY, BLACK, 
	BLACK, BLACK, GRAY, GRAY, GRAY, GRAY, BLACK, BLACK
};

const CRGB* const FRAMES[] PROGMEM = {FRAME1, FRAME2};
#define FRAMES_NUM 2